#############################################################################
# Makefile for building: FireApp
# Generated by qmake (3.1) (Qt 5.14.2)
# Project:  FireApp.pro
# Template: subdirs
# Command: D:\Qt\Qt5.14.2\5.14.2\mingw73_64\bin\qmake.exe -o Makefile FireApp.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = D:\Qt\Qt5.14.2\5.14.2\mingw73_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = D:\Qt\Qt5.14.2\5.14.2\mingw73_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = D:\Qt\Qt5.14.2\5.14.2\mingw73_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = 
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		sub-QtUi \
		sub-Skin \
		sub-App


sub-QtUi-qmake_all:  FORCE
	@if not exist QtUi\ mkdir QtUi\ & if not exist QtUi\ exit 1
	cd QtUi\ && $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\QtUi\QtUi.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
	cd QtUi\ && $(MAKE) -f Makefile qmake_all
sub-QtUi: FORCE
	@if not exist QtUi\ mkdir QtUi\ & if not exist QtUi\ exit 1
	cd QtUi\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\QtUi\QtUi.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-QtUi-make_first-ordered: FORCE
	@if not exist QtUi\ mkdir QtUi\ & if not exist QtUi\ exit 1
	cd QtUi\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\QtUi\QtUi.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-QtUi-make_first: FORCE
	@if not exist QtUi\ mkdir QtUi\ & if not exist QtUi\ exit 1
	cd QtUi\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\QtUi\QtUi.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-QtUi-all-ordered: FORCE
	@if not exist QtUi\ mkdir QtUi\ & if not exist QtUi\ exit 1
	cd QtUi\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\QtUi\QtUi.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-QtUi-all: FORCE
	@if not exist QtUi\ mkdir QtUi\ & if not exist QtUi\ exit 1
	cd QtUi\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\QtUi\QtUi.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-QtUi-clean-ordered: FORCE
	@if not exist QtUi\ mkdir QtUi\ & if not exist QtUi\ exit 1
	cd QtUi\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\QtUi\QtUi.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-QtUi-clean: FORCE
	@if not exist QtUi\ mkdir QtUi\ & if not exist QtUi\ exit 1
	cd QtUi\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\QtUi\QtUi.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-QtUi-distclean-ordered: FORCE
	@if not exist QtUi\ mkdir QtUi\ & if not exist QtUi\ exit 1
	cd QtUi\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\QtUi\QtUi.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-QtUi-distclean: FORCE
	@if not exist QtUi\ mkdir QtUi\ & if not exist QtUi\ exit 1
	cd QtUi\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\QtUi\QtUi.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-QtUi-install_subtargets-ordered: FORCE
	@if not exist QtUi\ mkdir QtUi\ & if not exist QtUi\ exit 1
	cd QtUi\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\QtUi\QtUi.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-QtUi-install_subtargets: FORCE
	@if not exist QtUi\ mkdir QtUi\ & if not exist QtUi\ exit 1
	cd QtUi\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\QtUi\QtUi.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-QtUi-uninstall_subtargets-ordered: FORCE
	@if not exist QtUi\ mkdir QtUi\ & if not exist QtUi\ exit 1
	cd QtUi\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\QtUi\QtUi.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-QtUi-uninstall_subtargets: FORCE
	@if not exist QtUi\ mkdir QtUi\ & if not exist QtUi\ exit 1
	cd QtUi\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\QtUi\QtUi.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-Skin-qmake_all: sub-QtUi-qmake_all FORCE
	@if not exist Skin\ mkdir Skin\ & if not exist Skin\ exit 1
	cd Skin\ && $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\Skin\Skin.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
	cd Skin\ && $(MAKE) -f Makefile qmake_all
sub-Skin: FORCE
	@if not exist Skin\ mkdir Skin\ & if not exist Skin\ exit 1
	cd Skin\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\Skin\Skin.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-Skin-make_first-ordered: sub-QtUi-make_first-ordered  FORCE
	@if not exist Skin\ mkdir Skin\ & if not exist Skin\ exit 1
	cd Skin\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\Skin\Skin.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-Skin-make_first: FORCE
	@if not exist Skin\ mkdir Skin\ & if not exist Skin\ exit 1
	cd Skin\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\Skin\Skin.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-Skin-all-ordered: sub-QtUi-all-ordered  FORCE
	@if not exist Skin\ mkdir Skin\ & if not exist Skin\ exit 1
	cd Skin\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\Skin\Skin.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-Skin-all: FORCE
	@if not exist Skin\ mkdir Skin\ & if not exist Skin\ exit 1
	cd Skin\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\Skin\Skin.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-Skin-clean-ordered: sub-QtUi-clean-ordered  FORCE
	@if not exist Skin\ mkdir Skin\ & if not exist Skin\ exit 1
	cd Skin\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\Skin\Skin.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-Skin-clean: FORCE
	@if not exist Skin\ mkdir Skin\ & if not exist Skin\ exit 1
	cd Skin\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\Skin\Skin.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-Skin-distclean-ordered: sub-QtUi-distclean-ordered  FORCE
	@if not exist Skin\ mkdir Skin\ & if not exist Skin\ exit 1
	cd Skin\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\Skin\Skin.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-Skin-distclean: FORCE
	@if not exist Skin\ mkdir Skin\ & if not exist Skin\ exit 1
	cd Skin\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\Skin\Skin.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-Skin-install_subtargets-ordered: sub-QtUi-install_subtargets-ordered  FORCE
	@if not exist Skin\ mkdir Skin\ & if not exist Skin\ exit 1
	cd Skin\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\Skin\Skin.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-Skin-install_subtargets: FORCE
	@if not exist Skin\ mkdir Skin\ & if not exist Skin\ exit 1
	cd Skin\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\Skin\Skin.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-Skin-uninstall_subtargets-ordered: sub-QtUi-uninstall_subtargets-ordered  FORCE
	@if not exist Skin\ mkdir Skin\ & if not exist Skin\ exit 1
	cd Skin\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\Skin\Skin.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-Skin-uninstall_subtargets: FORCE
	@if not exist Skin\ mkdir Skin\ & if not exist Skin\ exit 1
	cd Skin\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\Skin\Skin.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-App-qmake_all: sub-Skin-qmake_all FORCE
	@if not exist App\ mkdir App\ & if not exist App\ exit 1
	cd App\ && $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\App\App.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
	cd App\ && $(MAKE) -f Makefile qmake_all
sub-App: FORCE
	@if not exist App\ mkdir App\ & if not exist App\ exit 1
	cd App\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\App\App.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-App-make_first-ordered: sub-Skin-make_first-ordered  FORCE
	@if not exist App\ mkdir App\ & if not exist App\ exit 1
	cd App\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\App\App.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-App-make_first: FORCE
	@if not exist App\ mkdir App\ & if not exist App\ exit 1
	cd App\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\App\App.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-App-all-ordered: sub-Skin-all-ordered  FORCE
	@if not exist App\ mkdir App\ & if not exist App\ exit 1
	cd App\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\App\App.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-App-all: FORCE
	@if not exist App\ mkdir App\ & if not exist App\ exit 1
	cd App\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\App\App.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-App-clean-ordered: sub-Skin-clean-ordered  FORCE
	@if not exist App\ mkdir App\ & if not exist App\ exit 1
	cd App\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\App\App.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-App-clean: FORCE
	@if not exist App\ mkdir App\ & if not exist App\ exit 1
	cd App\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\App\App.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-App-distclean-ordered: sub-Skin-distclean-ordered  FORCE
	@if not exist App\ mkdir App\ & if not exist App\ exit 1
	cd App\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\App\App.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-App-distclean: FORCE
	@if not exist App\ mkdir App\ & if not exist App\ exit 1
	cd App\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\App\App.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-App-install_subtargets-ordered: sub-Skin-install_subtargets-ordered  FORCE
	@if not exist App\ mkdir App\ & if not exist App\ exit 1
	cd App\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\App\App.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-App-install_subtargets: FORCE
	@if not exist App\ mkdir App\ & if not exist App\ exit 1
	cd App\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\App\App.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-App-uninstall_subtargets-ordered: sub-Skin-uninstall_subtargets-ordered  FORCE
	@if not exist App\ mkdir App\ & if not exist App\ exit 1
	cd App\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\App\App.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-App-uninstall_subtargets: FORCE
	@if not exist App\ mkdir App\ & if not exist App\ exit 1
	cd App\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\App\App.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall

Makefile: FireApp.pro D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/win32-g++/qmake.conf D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/spec_pre.prf \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/qdevice.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/device_config.prf \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/common/sanitize.conf \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/common/gcc-base.conf \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/common/g++-base.conf \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/common/angle.conf \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/win32/windows_vulkan_sdk.prf \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/common/windows-vulkan.conf \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/common/g++-win32.conf \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/common/windows-desktop.conf \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/qconfig.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3danimation.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dcore.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dextras.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dinput.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dlogic.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquick.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3drender.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3drender_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axbase.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axbase_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axcontainer.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axcontainer_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axserver.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axserver_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_bluetooth.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_charts.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_charts_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_concurrent.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_core.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_core_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_datavisualization.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_dbus.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_dbus_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_designer.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_designer_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_gamepad.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_gui.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_gui_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_help.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_help_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_location.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_location_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_multimedia.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_network.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_network_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_networkauth.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_nfc.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_nfc_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_opengl.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_opengl_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_openglextensions.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_positioning.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_positioning_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_positioningquick.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_printsupport.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_purchasing.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qml.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qml_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmltest.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick3d.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick3drender.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick3drender_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_repparser.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_repparser_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_script.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_script_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_scripttools.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_scxml.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_scxml_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_sensors.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_sensors_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_serialbus.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_serialport.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_serialport_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_sql.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_sql_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_svg.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_svg_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_testlib.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_testlib_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_texttospeech.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_uiplugin.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_uitools.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_uitools_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_webchannel.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_websockets.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_websockets_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_widgets.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_widgets_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_winextras.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_winextras_private.pri \
		D:/Qt/QtXlsxWriter-master/mkspecs/modules-inst/qt_lib_xlsx.pri \
		D:/Qt/QtXlsxWriter-master/mkspecs/modules-inst/qt_lib_xlsx_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_xlsx.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_xml.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_xml_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_zlib_private.pri \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/qt_functions.prf \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/qt_config.prf \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/win32-g++/qmake.conf \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/exclusive_builds.prf \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/toolchain.prf \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/default_pre.prf \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/win32/default_pre.prf \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/resolve_config.prf \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/exclusive_builds_post.prf \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/default_post.prf \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/resources_functions.prf \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/qtquickcompiler.prf \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/precompile_header.prf \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/warn_on.prf \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/qmake_use.prf \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/file_copies.prf \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/win32/windows.prf \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/testcase_targets.prf \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/exceptions.prf \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/yacc.prf \
		D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/lex.prf \
		FireApp.pro
	$(QMAKE) -o Makefile FireApp.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/spec_pre.prf:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/qdevice.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/device_config.prf:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/common/sanitize.conf:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/common/gcc-base.conf:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/common/g++-base.conf:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/common/angle.conf:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/win32/windows_vulkan_sdk.prf:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/common/windows-vulkan.conf:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/common/g++-win32.conf:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/common/windows-desktop.conf:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/qconfig.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3danimation.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3danimation_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dcore.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dcore_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dextras.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dextras_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dinput.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dinput_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dlogic.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquick.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquick_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickextras.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickinput.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickrender.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3drender.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3drender_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axbase.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axbase_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axcontainer.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axcontainer_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axserver.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axserver_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_bluetooth.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_bodymovin_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_charts.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_charts_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_concurrent.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_concurrent_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_core.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_core_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_datavisualization.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_dbus.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_dbus_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_designer.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_designer_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_edid_support_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_egl_support_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_fb_support_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_gamepad.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_gamepad_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_gui.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_gui_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_help.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_help_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_location.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_location_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_multimedia.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_multimedia_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_network.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_network_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_networkauth.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_networkauth_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_nfc.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_nfc_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_opengl.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_opengl_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_openglextensions.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_positioning.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_positioning_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_positioningquick.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_printsupport.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_printsupport_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_purchasing.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_purchasing_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qml.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qml_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmlmodels.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmltest.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmltest_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick3d.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick3d_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick3dassetimport.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick3drender.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick3drender_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick3druntimerender.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick3dutils.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick3dutils_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickwidgets.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_remoteobjects.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_repparser.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_repparser_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_script.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_script_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_scripttools.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_scripttools_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_scxml.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_scxml_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_sensors.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_sensors_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_serialbus.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_serialbus_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_serialport.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_serialport_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_sql.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_sql_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_svg.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_svg_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_testlib.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_testlib_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_texttospeech.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_theme_support_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_uiplugin.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_uitools.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_uitools_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_vulkan_support_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_webchannel.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_webchannel_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_websockets.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_websockets_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_widgets.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_widgets_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_winextras.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_winextras_private.pri:
D:/Qt/QtXlsxWriter-master/mkspecs/modules-inst/qt_lib_xlsx.pri:
D:/Qt/QtXlsxWriter-master/mkspecs/modules-inst/qt_lib_xlsx_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_xlsx.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_xml.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_xml_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_zlib_private.pri:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/qt_functions.prf:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/qt_config.prf:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/win32-g++/qmake.conf:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/spec_post.prf:
.qmake.stash:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/exclusive_builds.prf:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/toolchain.prf:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/default_pre.prf:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/win32/default_pre.prf:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/resolve_config.prf:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/exclusive_builds_post.prf:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/default_post.prf:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/resources_functions.prf:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/qtquickcompiler.prf:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/precompile_header.prf:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/warn_on.prf:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/qmake_use.prf:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/file_copies.prf:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/win32/windows.prf:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/testcase_targets.prf:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/exceptions.prf:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/yacc.prf:
D:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/lex.prf:
FireApp.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile FireApp.pro -spec win32-g++ "CONFIG+=qtquickcompiler"

qmake_all: sub-QtUi-qmake_all sub-Skin-qmake_all sub-App-qmake_all FORCE

make_first: sub-QtUi-make_first-ordered sub-Skin-make_first-ordered sub-App-make_first-ordered  FORCE
all: sub-QtUi-all-ordered sub-Skin-all-ordered sub-App-all-ordered  FORCE
clean: sub-QtUi-clean-ordered sub-Skin-clean-ordered sub-App-clean-ordered  FORCE
distclean: sub-QtUi-distclean-ordered sub-Skin-distclean-ordered sub-App-distclean-ordered  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-QtUi-install_subtargets-ordered sub-Skin-install_subtargets-ordered sub-App-install_subtargets-ordered FORCE
uninstall_subtargets: sub-QtUi-uninstall_subtargets-ordered sub-Skin-uninstall_subtargets-ordered sub-App-uninstall_subtargets-ordered FORCE

sub-QtUi-debug_ordered:
	@if not exist QtUi\ mkdir QtUi\ & if not exist QtUi\ exit 1
	cd QtUi\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\QtUi\QtUi.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile debug
sub-Skin-debug_ordered: sub-QtUi-debug_ordered 
	@if not exist Skin\ mkdir Skin\ & if not exist Skin\ exit 1
	cd Skin\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\Skin\Skin.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile debug
sub-App-debug_ordered: sub-Skin-debug_ordered 
	@if not exist App\ mkdir App\ & if not exist App\ exit 1
	cd App\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\App\App.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile debug
debug: sub-QtUi-debug_ordered sub-Skin-debug_ordered sub-App-debug_ordered

sub-QtUi-release_ordered:
	@if not exist QtUi\ mkdir QtUi\ & if not exist QtUi\ exit 1
	cd QtUi\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\QtUi\QtUi.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile release
sub-Skin-release_ordered: sub-QtUi-release_ordered 
	@if not exist Skin\ mkdir Skin\ & if not exist Skin\ exit 1
	cd Skin\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\Skin\Skin.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile release
sub-App-release_ordered: sub-Skin-release_ordered 
	@if not exist App\ mkdir App\ & if not exist App\ exit 1
	cd App\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\App\App.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile release
release: sub-QtUi-release_ordered sub-Skin-release_ordered sub-App-release_ordered

sub-QtUi-check_ordered:
	@if not exist QtUi\ mkdir QtUi\ & if not exist QtUi\ exit 1
	cd QtUi\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\QtUi\QtUi.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
sub-Skin-check_ordered: sub-QtUi-check_ordered 
	@if not exist Skin\ mkdir Skin\ & if not exist Skin\ exit 1
	cd Skin\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\Skin\Skin.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
sub-App-check_ordered: sub-Skin-check_ordered 
	@if not exist App\ mkdir App\ & if not exist App\ exit 1
	cd App\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\App\App.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
check: sub-QtUi-check_ordered sub-Skin-check_ordered sub-App-check_ordered

sub-QtUi-benchmark_ordered:
	@if not exist QtUi\ mkdir QtUi\ & if not exist QtUi\ exit 1
	cd QtUi\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\QtUi\QtUi.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
sub-Skin-benchmark_ordered: sub-QtUi-benchmark_ordered 
	@if not exist Skin\ mkdir Skin\ & if not exist Skin\ exit 1
	cd Skin\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\Skin\Skin.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
sub-App-benchmark_ordered: sub-Skin-benchmark_ordered 
	@if not exist App\ mkdir App\ & if not exist App\ exit 1
	cd App\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\git_project\ebf_linux_qt_demo\App\App.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
benchmark: sub-QtUi-benchmark_ordered sub-Skin-benchmark_ordered sub-App-benchmark_ordered
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

